In [2]:
import tensorflow as tf

In [4]:
tf.__version__


'1.14.0'

In [7]:
hello=tf.constant("Hello")
hello

<tf.Tensor 'Const_2:0' shape=() dtype=string>

In [8]:
world=tf.constant("World")

In [9]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [11]:
type(world)

tensorflow.python.framework.ops.Tensor

In [12]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [21]:
with tf.Session() as sess:
    result=sess.run(hello+" " + world)
    

In [22]:
print(result)

b'Hello World'


In [23]:
var1=tf.constant(10)
var2=tf.constant(30)

In [24]:
var1+var2

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [25]:
with tf.Session() as ss:
    result=ss.run(var1+var2)

In [26]:
print(result)

40


In [27]:
cont=tf.constant(10)

In [28]:
matrix1=tf.fill((5,5),10)

In [30]:
zeroes=tf.zeros((5,5))

In [39]:
one=tf.ones((6,6))

In [40]:
const=[cont,matrix1,zeroes,one]

In [41]:
ses=tf.InteractiveSession()

In [46]:
for i in const:
#    print(ses.run(i))
     print(i.eval())
     print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]




In [47]:
a=tf.constant([[2,3],[4,5]])

In [49]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [50]:
b=tf.constant([[10],[100]])

In [52]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [53]:
result=tf.matmul(a,b)

In [55]:
ses.run(result)

array([[320],
       [540]])